Kni\ThomasBundle\Entity\Files:
    type: entity
    table: null
    repositoryClass: Kni\ThomasBundle\Entity\FilesRepository
    fields:
        fileId:
            type: integer
            id: true
            column: file_id
            generator:
                strategy: AUTO
        fileName:
            type: string
            length: '45'
            column: file_name
        fileSrc:
            type: string
            length: '145'
            column: file_src
        stepId:
            type: integer
            column: step_id
    lifecycleCallbacks: {  }
