# app/config/parameters.yml
parameters:
    database_driver:    pdo_mysql
    database_host:      localhost
    database_name:      thomas
    database_user:      root
    database_password:  
    database_port:      3306

    locale:             pl
    
    secret:             ThisTokenIsNotSoSecretChangeIt
