kni_thomas:
    resource: "@KniThomasBundle/Resources/config/routing.yml"
    prefix:   /

home:
    path: /
    defaults:  { _controller: KniThomasBundle:Secured:login }

thomas:
    resource: "@KniThomasBundle/Controller"
    type:     annotation
    
login_page:
    resource: "@KniThomasBundle/Controller/SecuredController.php"
    type:     annotation