jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Kni\ThomasBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        user_db:
            entity: { class: Kni\ThomasBundle\Entity\User, property: username }
        
        
        
        
    firewalls:

        login:
            pattern:  ^/profile/login$
            security: false

        secured_area:
            pattern:    ^/profile/
            form_login:
                check_path: login_check
                login_path: login_page
                always_use_default_target_path: true
                default_target_path: /profile/index
            logout:
                path:   logout
                target: page
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/profile, roles: ROLE_USER }
